-- AlterTable
ALTER TABLE "Invoice"
  ADD COLUMN "cgstAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
  ADD COLUMN "sgstAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
  ADD COLUMN "igstAmount" DECIMAL(65,30) NOT NULL DEFAULT 0,
  ADD COLUMN "interState" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "sacCode" TEXT NOT NULL DEFAULT '998314',
  ADD COLUMN "natureOfSupply" TEXT NOT NULL DEFAULT 'B2B',
  ADD COLUMN "placeOfSupply" TEXT;
